### ISSUE TITLE
generated pom not uploaded

### ISSUE THREAD

**Issue by cubefriendly** [frugalmechanic/fm-sbt-s3-resolver#10]
Hi!
I just integrated your plugin to my project and everything works great expect for one thing.

I see that everything is uploaded except the pom file. Do you have any idea why?

Still investigating ..

**Comment by tpunder** [comment]
Do you have ```publishMavenStyle := true``` in your build.sbt file?

**Comment by cubefriendly** [comment]
No I don't. Let me try that

**Comment by cubefriendly** [comment]
It works! Thank you so much and your plugin rocks!
