### ISSUE TITLE
Error 403 while fetching deps

### ISSUE THREAD

**Issue by paulovictorv** [frugalmechanic/fm-sbt-s3-resolver#12]
Hello, I've being using your plugin successfully for about 6 months, but today, all of the sudden every request I do to fetch my dependencies fails with a 403 code.

I've tried the following already:
* Updating my AWS credentials, no luck
* Setting all of the deps as public, still 403 code
* Checking if there was something wrong with my firewall settings, everything looks fine
* Tried resolving the dependencies using another network (not the one from work), still forbidden
* Specified my credentials using all of the methods listed on the README, no luck

I don't think this is a specific issue with your plugin, but maybe someone can point me a possible solution.

Also, I have projects using SBT and projects using Maven. Those that use Maven resolve all of my S3 deps just fine. SBT is the only one that is failing.

Thanks in advance!

**Comment by tpunder** [comment]
I'm not sure what the problem would be.  All of our projects using the plugin are still working fine.

Can you try using the AWS Java SDK directly with your credentials to see if you can replicate the 403 response code?

**Comment by paulovictorv** [comment]
Actually, the maven s3 resolver works with no issues with the same credentials.

Only fm-sbt-s3-resolver is complaining about my credentials and throwing 403 around :/

But for ease of mind, I've tested with a dummy java code and it works..

**Comment by tpunder** [comment]
Can you try version 0.6.0?  I upgraded to the latest AWS SDK and added some logging for which AWS Access Key ID is being used for which bucket.

**Comment by tpunder** [comment]
I did start seeing some 403 errors on one of my production servers using a read-only AWS key.  Still not sure what was causing it but version 0.6.0 seems to clear it up for me.

**Comment by paulovictorv** [comment]
Sorry for the late reply.

Version 0.6.0 seems to fix the problem. Thank you for taking the time to fix it :)

I'm closing this issue, cheers.
