### ISSUE TITLE
Enable HTTPS for private repo's

### ISSUE THREAD

**Issue by mdedetrich** [frugalmechanic/fm-sbt-s3-resolver#14]
Would it be possible to provide an option to enable HTTPS for s3 buckets (in my case private, which doesn't have a https specific url because it wasn't made public)?

This may already be possible (or it may not be possible at all), however according to S3 docs, you should be able to use https communication with S3 buckets

**Comment by tpunder** [comment]
According to the AWS Java SDK docs it should default to using HTTPS.  Are you seeing non HTTPS traffic?

**Comment by mdedetrich** [comment]
It should be fine then.

I just started using `fm-sbt-s3-resolver` and I was wondering if traffic was encrypted. If its done this way by default, then it should be all good
