### ISSUE TITLE
Using plugin on IntelliJ IDE

### ISSUE THREAD

**Issue by barbaragomes** [frugalmechanic/fm-sbt-s3-resolver#20]
Hey There,

By any chance you have tried to use the plugin on IntelliJ?

If I use the SBT console and compile my code, the artifact is dowloaded successfully.
But if I delete the artifact from my cache and IntelliJ tries to resolve the dependency, it is not able to find the credentials on my environment variables to connect to my S3 repo.

```(*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: MY_DEPENDENCY_2.11: Unable to load AWS credentials from any provider in the chain```

My project is using Scala 2.11. I'm not sure if that could be the problem since the `sbt compile` command works fine.

Thanks!

**Comment by mamdouhweb** [comment]
+1... any luck with this one?

**Comment by tpunder** [comment]
I haven't used the plugin with IntelliJ but I know @er1c is successfully using it.

**Comment by er1c** [comment]
I _think_ it works out of the box for OSX, but with Windows you need to specify the tokens through either JVM or environment variables;

There's two different ways to do this, either add the environment variables to your global environment (AWS_ACCESS_KEY_ID=XXXX; and AWS_SECRET_KEY=YYYY), or you can add it to the scala compile server JVM options (-Daws.accessKeyId=XXXXXXX -Daws.secretKey=XXXXXXXX)

There's actually multiple places you can specify the JVM options within intellij:

During project import:
![google chrome](https://cloud.githubusercontent.com/assets/64685/16277051/0506cf4e-3866-11e6-9ea2-2c002b74a8e4.png)

Or under the Scala Compile Server Preferences:
![intellij idea](https://cloud.githubusercontent.com/assets/64685/16277056/0a2055ae-3866-11e6-82e7-2413263f0776.png)

If you have custom "SBT Tasks" you can also specify the keys in your Run/Debug Configurations here:
![intellij idea](https://cloud.githubusercontent.com/assets/64685/16277117/5b887f3e-3866-11e6-8163-572e98c61d10.png)

**Comment by barbaragomes** [comment]
The only way I was able to get it working was using the `~/.aws/credential` file (I'm using the latest IntelliJ CE).

Inside your `~/.aws/credential` add:

```[default]
aws_access_key_id={NO_QUOTES_KEY}
aws_secret_access_key={NO_QUOTES_SECRET_KEY}
```

The profile name inside `[]` has to be `default`. It did not work with any other profile name.

I will try the other way @er1c talked about.

Thanks!

**Comment by er1c** [comment]
@barbaragomes how do you usually specify the credentials?  I use a `~/.sbt/.<bucket name>_s3credentials` file for both sbt/intellij

**Comment by barbaragomes** [comment]
@er1c I haven't tried to specify the credentials in `~/.sbt/.<bucket name>_s3credentials` file.
I'm specifying it in a `~/.aws/credential` file as I mentioned on my previous comment and it works for IntelliJ and SBT as well.

**Comment by er1c** [comment]
@barbaragomes Right, I was just curious what you were "trying before" that prompted the issue/question around this plugin not working w/intellij

**Comment by barbaragomes** [comment]
@er1c Ow, okay, got it =P
I was trying to specify using Environment Variables:

- AWS_ACCESS_KEY_ID_BUCKET_NAME
- AWS_SECRET_KEY_BUCKET_NAME

And this was working only through SBT console, but IntelliJ wasn't able to find it.

**Comment by er1c** [comment]
@barbaragomes  for OSX you need to update the environment through the `launchctl setenv` for it to take effect for clicking the icon in the tray (http://stackoverflow.com/questions/603785/environment-variables-in-mac-os-x)  the normal `~/.bashrc` only applies to your iTerm environment.

The other way you can do it is to edit /Applications/IntelliJ\ IDEA\ CE.app/Contents/Info.plist and add them directly to the JVM options for intellij runtime environment:
```
      <key>VMOptions</key>
      <string>-Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -Xbootclasspath/a:../lib/boot.jar</string>
```

**Comment by barbaragomes** [comment]
@er1c Thanks a lot. That did the trick =)
