### ISSUE TITLE
Snapshot versions not being updated

### ISSUE THREAD

**Issue by rgladwell** [frugalmechanic/fm-sbt-s3-resolver#21]
Snapshot version do not appear to be updated on a typical sbt command (i.e. `sbt compile`).

Steps to reproduce:

 1. `sbt publish` snapshot dependency
 2. `sbt compile` in a project consuming the same snapshot dependnecy.

Expected result: `/.ivy2/cache` should be updated with new version.

Actual result: `/.ivy2/cache` contains the first version of the snapshot initially downloaded. Fails to download subsequent modified snapshot dependencies.

Snapshots are only updated if marked with `changing()` or an `sbt update` command.

Note, according to the official SBT documentation snapshot version should always be freshly downloaded:

http://www.scala-sbt.org/1.0/docs/Dependency-Management-Flow.html#Notes

This issue also appears to be intermittant: sometimes a snapshot dependency will randomly dowload an update on an `sbt compile`.

**Comment by tpunder** [comment]
Is this issue specific to fm-sbt-s3-resolver?  I'm pretty sure I see the same issue with SNAPSHOT versions from Sonatype.

**Comment by rgladwell** [comment]
You are correct, this issue can be reproduced publishing/downloading from a local, test Artifactory repository.
