### ISSUE TITLE
Will not work if AWS profile is generated by AWS adfs plugin with session token

### ISSUE THREAD

**Issue by tthaomo** [frugalmechanic/fm-sbt-s3-resolver#24]
I used this plugin (https://github.com/venth/aws-adfs) to generate AWS adfs profile on the fly.

Beside `aws_access_key_id` and `aws_secret_access_key`, it also generates `aws_session_token` which blocks the s3 resolver working.

**Comment by tpunder** [comment]
Where does the `aws_session_token` need to be passed to?  Is there a special `AWSCredentialsProvider` that needs to be used?

Do the Custom S3 Credentials solve this for you?  https://github.com/frugalmechanic/fm-sbt-s3-resolver#custom-s3-credentials

**Comment by tpunder** [comment]
Please re-open if this is still an issue.

**Comment by dtboctor** [comment]
Did you get this to work?  What provider did you use?
