### ISSUE TITLE
looking for pom files in s3

### ISSUE THREAD

**Issue by timchan-lumoslabs** [frugalmechanic/fm-sbt-s3-resolver#25]
We use this plugin to publish artifacts to s3. they appear to be ivy style. I see an ivy.xml file in the directory in s3. 

This is the first time I've tried depending on an artifact in another project that is in our s3 bucket. I see warnings that show an s3 path that contains a .pom file. Is it expecting to find maven formatted artifacts? How do I get this to look for ivy artifacts in s3?

**Comment by tpunder** [comment]
Good question.  My plugin doesn't do anything specific to Maven or IVY specific artifacts or layouts.  All it does is enable SBT to read/write files using the s3:// protocol.

Looking at the SBT docs (http://www.scala-sbt.org/0.13/docs/Resolvers.html) it looks like maybe you can do something like:

```
resolvers += Resolver.url("my-test-repo", url("s3://example.org/repo-releases/"))(Resolver.ivyStylePatterns)
```

Maybe this syntax works too?
```
resolvers += ("my-test-repo" at "s3://example.org/repo-releases/")(Resolver.ivyStylePatterns)
```

If you get it working let me know and I'll add the example to the docs.

**Comment by timchan-lumoslabs** [comment]
Our publish setting had `publishMavenStyle := false`. Setting it to `true` solved my issue.

**Comment by mscharley** [comment]
For the record:

We use ivy-style with our S3 box and the first example above worked to resolve into it. It'd be nice to get an example of using ivy style patterns in the README.

```
resolvers += Resolver.url("my-test-repo", url("s3://example.org/repo-releases/"))(Resolver.ivyStylePatterns)
```

**Comment by tpunder** [comment]
@mscharley Do these examples look correct?

https://github.com/frugalmechanic/fm-sbt-s3-resolver/blob/master/README.md#resolving-dependencies-via-s3

https://github.com/frugalmechanic/fm-sbt-s3-resolver/blob/master/README.md#publishing-to-s3

**Comment by mscharley** [comment]
I've only tried resolving, but that worked with that example.
