### ISSUE TITLE
can't resolve artifacts that was published with fm-sbt-s3-resolver

### ISSUE THREAD

**Issue by Liorba** [frugalmechanic/fm-sbt-s3-resolver#26]
Hey I use fm-sbt-s3-resolver to publish my code to s3 and it works great and put the following files in the folder:
```
myProject_2.11-1.0.12-javadoc.jar
myProject_2.11-1.0.12-javadoc.jar.md5
myProject_2.11-1.0.12-javadoc.jar.sha1
myProject_2.11-1.0.12-sources.jar
myProject_2.11-1.0.12-sources.jar.md5
myProject_2.11-1.0.12-sources.jar.sha1
myProject_2.11-1.0.12.jar
myProject_2.11-1.0.12.jar.md5
myProject_2.11-1.0.12.jar.sha1
ivy-1.0.12.xml
ivy-1.0.12.xml.md5
ivy-1.0.12.xml.sha1
```
but when I tried to resolve it ,it looks for myProject_2.11-1.0.12.pom which wasn't created during publish(as seen above)
is there any way to solve it?

Thanks

**Comment by tpunder** [comment]
Sounds like a similar issue to https://github.com/frugalmechanic/fm-sbt-s3-resolver/issues/25

Are you setting `publishMavenStyle := false`?  That would disable publishing of the POM file.

**Comment by Liorba** [comment]
The issue is with the resolver.
It tries to find the pom file in s3 which does not exists.
is there a away to set _fm-sbt-s3-resolver_ to look for the ivy xml file instead?

**Comment by tpunder** [comment]
Right, `publishMavenStyle := true` enables publishing of the POM file.

I'm a little confused by what you are trying to do.  Did you build and publish Spark to your SBT bucket?  Can you post your build.sbt file?

**Comment by Liorba** [comment]
what I'm trying to do is to publish my project (lets call him project 1) which have maven dependencies like(typesafe config and mysql connector)
I have another project (lets call hime project 2) which has project one as a dependency.
what I expected to happen is:

1.  that the resolver will take project 1's pom file and try to resolve the written dependencies form maven and not form s3
2.  dependency in scope provided would not appear in project1 generated pom file

project 1 build.sbt:

```
name := "project1"

version := "1.0.0"

organization := "me"

scalaVersion := "2.11.8"

resolvers += "Spark Package Main Repo" at "https://dl.bintray.com/spark-packages/maven"

libraryDependencies += "org.apache.spark" % "spark-core_2.11" % "2.0.0" % Provided
libraryDependencies += "org.apache.spark" % "spark-sql_2.11" % "2.1.0" % Provided
libraryDependencies += "org.apache.spark" % "spark-streaming-kinesis-asl_2.11" % "2.1.0" % Provided
libraryDependencies += "mysql" % "mysql-connector-java" % "5.1.6"
libraryDependencies += "harsha2010" % "magellan" % "1.0.4-s_2.11"
libraryDependencies += "com.amazonaws" % "amazon-kinesis-client" % "1.7.2"
libraryDependencies += "net.sf.opencsv" % "opencsv" % "2.3"
libraryDependencies += "com.typesafe.play" % "play-json_2.11" % "2.4.10"
libraryDependencies += "redis.clients" % "jedis" % "2.9.0"
libraryDependencies += "com.typesafe" % "config" % "1.3.1"
libraryDependencies += "org.apache.logging.log4j" % "log4j-core" % "2.8.1"
libraryDependencies += "org.apache.logging.log4j" % "log4j-api" % "2.8.1"
libraryDependencies += "org.apache.logging.log4j" %% "log4j-api-scala" % "2.8.1"

publishMavenStyle := true
publishTo := Some("My Sbt Bucket " at "s3://my-sbt-bucket")
```
 you can see all spark dependencies are in `provided` scope

project 2 build.sbt

```
name := "project2"

version := "1.0"

scalaVersion := "2.11.8"

resolvers += "Spark Package Main Repo" at "https://dl.bintray.com/spark-packages/maven"

resolvers += ("My Sbt Bucket" at "s3://my-sbt-bucket" )

libraryDependencies += "me" % "project1_2.11" % "1.0.1"
libraryDependencies += "org.apache.spark" % "spark-core_2.11" % "2.1.0"
libraryDependencies += "org.apache.spark" % "spark-sql_2.11" % "2.1.0"
libraryDependencies += "org.apache.spark" % "spark-streaming_2.11" % "2.1.0"
libraryDependencies += "org.apache.spark" % "spark-streaming-kinesis-asl_2.11" % "2.1.0"
libraryDependencies += "org.isuper" % "s2-geometry-library-java" % "0.0.1"

```

**Comment by tpunder** [comment]
I'm not sure what's going on here.

Are you using any other SBT plugins?

The `java.net.MalformedURLException: unknown protocol: s3` error makes it sound like fm-sbt-s3-resolver isn't being included properly or it's being initialized for some reason.

**Comment by Liorba** [comment]
this is my plugins.sbt 

```
logLevel := sbt.Level.Info
addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.9.0")
```

**Comment by tpunder** [comment]
Hi @Liorba 

I've created a test repo using your build.sbt files:  https://github.com/tpunder/fm-sbt-s3-resolver-issue-26

I did a `publish` in `project1` and then did an `update` from `project2` and everything worked fine.  Can you take a look and let me know how your setup differs from mine?

**Comment by cosmincatalin** [comment]
I have a similar problem. I use `sbt % 1.0.2`,`fm-sbt-s3-resolver % 0.12.0` and get:

```
unresolved dependency: org.apache.spark#spark-core_2.11;2.2.0: Resolution failed several times for dependency: org.apache.spark#spark-core_2.11;2.2.0 {provided=[default(compile)]}::
```

In my project I have:

```
libraryDependencies ++= {
    val sparkVersion = "2.2.0"
    Seq(
        "org.apache.spark" %% "spark-core" % sparkVersion % Provided
    )
}
```

It's like the `Provided` is forced solved by the s3 wagon only.

**Comment by onema** [comment]
@cosmincatalin I was having a similar issue, I downgraded from fm-sbt-s3-resolver `0.12.0` to `0.11.0` and is working now

**Comment by onema** [comment]
@Liorba, also I was experiencing this same problem not being able to install the dependency package. I eventually got it working by using these steps

1. Used `addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.11.0")` in `projects/plugin.sbt` both in the dependency package and the application package
1. In the dependency package, I set `publishMavenStyle := true` setting it to false and using the ivy style resolver in the application package didn't work as I kept getting `UNRESOLVED DEPENDENCIES`
1. I used the following URL form `s3://s3-[REGION].amazonaws.com/[BUCKET]/[OPTIONAL_PATH]` as it was complaining that it needed the region. 
```
om.amazonaws.services.s3.model.AmazonS3Exception: The bucket is in this region: us-east-1. Please use this region to retry the request (Service: Amazon S3; Status Code: 301; Error Code: 301 Moved Permanently;
```

In the end I was able to get it to publish the dependency package, install the dependency in an application, compiled and run the application.

I hope this helps.

**Comment by tpunder** [comment]
Please re-open if this is still an issue.  There were a number of issues with the early SBT 1.0.x releases that were causing problems.  SBT 1.0.4 was the first version that actually worked properly.  I'm currently using SBT 1.1.5 and version 0.14.0 of this plugin with no problems.

**Comment by oripwk** [comment]
I am having the same issue with version 0.19.0 and sbt 1.3.7
