### ISSUE TITLE
"Repository for publishing is not specified" in multimodule build with publishArtifacts := false

### ISSUE THREAD

**Issue by mcamou** [frugalmechanic/fm-sbt-s3-resolver#29]
I have a multi-module sbt build in which only some of the submodules should be published. I have set up `publishArtifact := true` in those that should be published, and `publishArtifact := false` in those that should not. I am also setting `publishTo := Some(repo)` in those that should be published, and `publishTo := None` in those that should not.

The standard Ivy publish plugin works fine with this. However, with fm-sbt-s3-resolver, I get `Repository for publishing is not specified` errors for those repositories that have `publishArtifact := false`.

**Comment by tpunder** [comment]
Can you share your build.sbt file that is causing this error?

**Comment by tpunder** [comment]
This actually sounds similar to an issue I've seen.  I'm not sure if it's related to the fm-sbt-s3-resolver plugin or not since it happens for me in projects that only publish to Sonatype.  Here is what my settings end up looking like for modules that I don't want published:

```scala
settings(
  publish := {},
  publishLocal := {},
  publishArtifact := false,
  publishTo := Some(Resolver.file("Unused transient repository", file("target/unusedrepo"))) // http://stackoverflow.com/a/18522706
)
```
