### ISSUE TITLE
Did you remove fm-s3 from bintray?

### ISSUE THREAD

**Issue by tzimisce012** [frugalmechanic/fm-sbt-s3-resolver#35]
Couple days ago, when we try to compile the frugal s3 plugin we are getting the following error:

```
[warn] Host repo.typesafe.com not found. url=https://repo.typesafe.com/typesafe/ivy-releases/com.frugalmechanic/fm-sbt-s3-resolver/scala_2.10/sbt_0.13/0.11.0/ivys/ivy.xml
[info] You probably access the destination server through a proxy server that is not well configured.
```

When I check the link by myself I just realized that the plugin is not available anymore.

Is this normal?

**Comment by tpunder** [comment]
I'm not sure what is trying to access `repo.typesafe.com`.

fm-sbt-s3-resolver is published to Sonatype (https://oss.sonatype.org/content/repositories/releases/com/frugalmechanic/fm-sbt-s3-resolver_2.10_0.13/) which is then synced to Maven central (https://repo1.maven.org/maven2/com/frugalmechanic/fm-sbt-s3-resolver_2.10_0.13/)

**Comment by tzimisce012** [comment]
Ok, Ill do a further check

**Comment by tpunder** [comment]
Closing this for now
