### ISSUE TITLE
AWS S3 access without credentials

### ISSUE THREAD

**Issue by anemkov** [frugalmechanic/fm-sbt-s3-resolver#41]
We are using SBT with your plugin within AWS CodeBuild feature. We do not need specify credentials anywhere because we use AWS service roles. 

If we do not specify AWS keys, the build process stuck with messages like:
**S3URLHandler - Looking up AWS Credentials for bucket:** 

Is there is a way to prevent usage AWS credentials?

**Comment by tpunder** [comment]
Can you provide any more details about your setup?  In general, using IAM Roles for EC2 Instances should work fine but I'm not sure if there is something different about CodeBuild.  If all you are seeing is:

```
S3URLHandler - Looking up AWS Credentials for bucket:
```
Then that makes me think it's not detecting the bucket you are trying to access.

**Comment by tpunder** [comment]
Also, if the default credentials provider chain doesn't work for you then you can specify your own.  

I've added documentation on how to do this in the README.md file:  https://github.com/frugalmechanic/fm-sbt-s3-resolver#custom-s3-credentials

**Comment by tpunder** [comment]
If this is still an issue please re-open.
