### ISSUE TITLE
Plugin does not handle ${packaging.type} in package name

### ISSUE THREAD

**Issue by margussipria** [frugalmechanic/fm-sbt-s3-resolver#45]
I don't know if this is really SBT bug, I opened issue https://github.com/sbt/sbt/issues/4005, but it maybe resolved by handling exception in this plugin directly.

There is also example [here](https://github.com/margussipria/sbt-bug-javax.ws.rs-api)

Issue:
When pom is using Maven supported package magic and SBT can't handle it, even with fixes this plugin fails with exception when resolving packages.

**Comment by tpunder** [comment]
Your fix was released as version `0.15.0`

**Comment by margussipria** [comment]
Yes, and it works, I thought project maintainer would close this
