### ISSUE TITLE
Don't log when URLStreamHandler is already installed

### ISSUE THREAD

**Issue by analytically** [frugalmechanic/fm-sbt-s3-resolver#48]
For each module this
"URLStreamHandler is already installed" is logged when starting SBT. Unnecessary IMHO.

**Comment by tpunder** [comment]
Thanks for reminding me.  This has been on my list for a while.  Here is the change:  https://github.com/frugalmechanic/fm-sbt-s3-resolver/commit/a1e246359baf8395e9c9f3cd6fbccceaab8b931e

Published as `0.16.0-SNAPSHOT`

**Comment by analytically** [comment]
Thanks, this merits a 0.16.0 release for me ;-)

**Comment by tpunder** [comment]
`0.16.0` released!  Should sync to maven central in 10-20mins.
