### ISSUE TITLE
Warning about resolving snapshots.

### ISSUE THREAD

**Issue by codenamestif** [frugalmechanic/fm-sbt-s3-resolver#54]
The problem is when i try to resolve lots of snapshots on purpose, i get lots of warnings in console:
```[warn] Resolving a snapshot version. It's going to be slow unless you use `updateOptions := updateOptions.value.withLatestSnapshots(false)` options.``` Would be awesome to have an ability to turn this warning off.

**Comment by tpunder** [comment]
That's an SBT warning and has nothing to do with the fm-sbt-s3-resolver plugin.

**Comment by codenamestif** [comment]
Ah, sorry, my bad. Yes, that's sent by sbt.
