### ISSUE TITLE
[question] scala 2.11

### ISSUE THREAD

**Issue by andypetrella** [frugalmechanic/fm-sbt-s3-resolver#9]
hello!

Great stuffs here! Thanks for sharing!
I was wondering if it would be possible to have the cross version (2.11) deployed as well?

Because I'm just finishing the integration of this project in the [spark-notebook](https://github.com/andypetrella/spark-notebook/) in order to download deps even on s3... but I also have to support scala-2.11 :-(.

wdyt?
thanks again
cheers,
andy

**Comment by tpunder** [comment]
Is there a version of SBT that supports writing plugins using Scala 2.11?  I thought SBT 0.13.x was still all Scala 2.10?

**Comment by andypetrella** [comment]
hehe good point. Actually [here](https://github.com/sbt/sbt/blob/0.13/build.sbt) I see some stuffs related to `2.11` but it could be the case that it's still not available for scala 2.10 (so I might have bad moments).

It sounds like a noob question, but do you see something for 2.11? Maybe shall we ask, I dunno, @jsuereth?

**Comment by tpunder** [comment]
What exactly are you trying to do?  Are you seeing error messages trying to use the fm-sbt-s3-resolver plugin?

**Comment by andypetrella** [comment]
nope, in the scala 2.11 branch I need to use SBT to resolve deps that I inject int he spark-repl.

Clearly not an issue of this project, so I'll first try to find a version (1.0?) that can be used with scala 2.11.

**Comment by tpunder** [comment]
Closing this since I don't think it was an issue with fm-sbt-s3-resolver.
